name: pull-request into test

on:
  pull_request:
    branches:
      - test
    types: [opened, reopened, synchronize]
jobs:
  gradle_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: oracle
          java-version: 20
      - name: setup gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.1.1
      - name: test
        run: gradle test
